### ISSUE TITLE
rediscluster.exceptions.RedisClusterException: Slot "13145" not covered by the cluster. "skip_full_coverage_check=True"

### ISSUE THREAD

**Issue by umang92** [Grokzen/redis-py-cluster#350]
Hello,

I am using redis-py-cluster 2.0.0 and AWS Elasticache Clustered Mode Redis. 

When I initialize my RedisCluster client with skip_full_coverage_check=False, I get the following error:
```redis.exceptions.ResponseError: unknown command `CONFIG`, with args beginning with: `GET`, `cluster-require-full-coverage`,```

It gets resolved when I use skip_full_coverage_check=True.

After this, I tried primary failover by initiating failover in one of the shards. After the failover finished one of my containers connecting with the Redis started throwing errors like below:

```rediscluster.exceptions.RedisClusterException: Slot "13145" not covered by the cluster. "skip_full_coverage_check=True"```

Strange thing is that the other containers were working fine after the failover. What can be the issue?

Thanks,
Umang.

**Comment by Grokzen** [comment]
Basically this is technicall intended from the client side of things. What happens when you start a failover is that the client picks this up and it tries to rebuild the slots cache and when your slot is not covered during the failover event timeframe, that error is pushed up by the client since you technically told it to ignore if your cluster is broken or not, it is up to your code to sort it out if you want that behaviour from your client.

I do get why this would be wrong from a usability pov when using the aws elasticache cluster mode. It might be needed to split the config into two new options instead of one. One that controlls if `cluster-require-full-coverage` is really needed or not. And one that will deal with how the client should behave internally. I would have to think about this tho, and the only suggestion i can give you right now is that you need to sort this out in your code layer for now if you keep using this mode/feature

**Comment by umang92** [comment]
Sure. But what I am unable to understand is why this behavior is not consistent between different containers running the same code. One of the containers went into the 'bad' state and it was only resolved when I restarted and recreated the RedisCluster client. Any particular suggestions for handling these scenarios in the python code?

**Comment by Grokzen** [comment]
By container, do you mean a container that is running your client code? or do you mean the redis server itself that goes into a bad state?

The reason why this is not really consistent between your clients, is that the client code will only go into the recovery mode if you issue a command to a slot that belongs to the node that failed and is no longer covered by your cluster. If you have 10 different clients running and they randomly issue commands to your cluster, some of them will hit different redis nodes at different times based on usage pattern. So even if you have a steady stream of commands being issued, maybe only two of your client instances will issue a command to a node that is on the redis node that is failing over. Becuase your clients will only fail out if you acctually issue a command to the cluster while a failover event is happening. If your clients is idle during that time, your clients will still belive the cluster is intact, and when all nodes is up again, even if they have migrated slots, the client will then automatically recover.

The only real way you can handle this case in your code is to wrap your redis client calls into a sort of retry logic if this is a case that you must ensure that is saved into the cluster. It all depends on your buisiness logic really. If you use it for a cache, maybe you can just ignore the issue and just not let the item cache that time and let it cache the next time or something. If your code is more important that it executes reliably, then either consider to wrap the calls in a retry loop where it waits or attempts to issue your command a certain number of times, and if you get this specific exception, you let the client wait for some ammount of time before retrying, or you can just simply fail out fast and hard while your cluster is being rebuilt and going back into a good state again.

**Comment by umang92** [comment]
By container, I meant the container that is running my client code.

I am able to reproduce this issue most of the time I am testing a primary failover. I have 50 containers that are running a python Redis client which performs Redis list operations of lpush and rpop.  I run this set up on an Aws Elasticahe with Cluster mode with 3 shards, 2 read replicas per shard. Almost 100-200 Redis list operations happen per second.

Now as the load is running, I perform a primary failover in one of the shards. I start to see "Slot "8011" not covered by the cluster. "skip_full_coverage_check=True"" errors in one of the containers. Other containers seem to handle the failover gracefully with few TTL exhausted errors which auto resolved in few seconds.

The Slot not covered error keeps on coming even after the failover is completed and read replica is upgraded to become a new primary. This gets resolved only after I restart the container, which would recreate the RedisClient.

So I do not think that retries would help here as the RedisClient itself into an 'irrecoverable' state.

**Comment by Grokzen** [comment]
I will see if i can reproduce the error in some way. What i find really strange is that some of your clients really fail out and recover in the way that it should, and some of the nodes just get into irrecoverable state where it just keeps popping up that error from the client side. So there might be some really obscure path through the client code where the client would not trigger the switch to really rebuild the cluster as the failover begun to happen.

**Comment by Grokzen** [comment]
@umang92 Is is possible that you can provide a full stack trace of the problem here? I would like to see the exact path through the code that your client takes when it reaches the exception. There is only one place where the exception occurs, but i am not sure how it get there.

Also a more direct solution to your exception problem in the meantime would be something like this in your client code layer.

```
rc = RedisCluster(..., skip_full_coverage_check=True, ...)

try:
  ...
  rc.set(... , ...)
  ...
except RedisClusterException as e:
  rc.refresh_table_asap = True
```

If you do this, the next time you execute a command on the client class, it will triggere the `connection_pool.nodes.initialize()` method that will refresh the entire slots cache and nodes cachrefresh_table_asape as well on next command execution. Then you only have to sort out the retry part if your command is a must to be executed, but if you try this, it might just recover your containers without the need to restart them. The downside is that you either have to wrap the command execution in try/catch blocks all over, or make a wrapper class around it that overwrites the execute_command method with your wrapper code. So you have to decide what kind of tradeoff you want to have with performance vs ease of use.

**Comment by umang92** [comment]
Thanks @Grokzen I'll try your recommendation now. Here is the full stack trace of the error.

```

rediscluster.exceptions.RedisClusterException: Slot "6986" not covered by the cluster. "skip_full_coverage_check=True"
--
  | File "/app/python/rediscluster/connection.py", line 338, in get_master_node_by_slot
  | slot=slot, skip_full_coverage_check=self.nodes._skip_full_coverage_check,
  | File "/app/python/rediscluster/connection.py", line 344, in get_node_by_slot
  | File "/app/python/rediscluster/client.py", line 393, in execute_command
  | File "/app/python/rediscluster/utils.py", line 101, in inner
  | return self.get_master_node_by_slot(slot)
  | node = self.connection_pool.get_node_by_slot(slot, self.read_from_replicas and (command in self.READ_COMMANDS))
  | return func(*args, **kwargs)
  | File "/app/python/redis/client.py", line 1554, in lpush
  | File "/app/python/sensei_sdk/redislist_chunked_content.py", line 123, in close
  | File "/app/python/sensei_sdk/redislist_chunked_content.py", line 42, in __exit__
  | return self.execute_command('LPUSH', name, *values)
  | self._rserver.lpush(self.content_ref1, _bytes) 

```

**Comment by umang92** [comment]
@Grokzen  I applied your suggestion and it resolved the issue. With this, the issue is no more reproducible. 
But I would wait for the fix from your side in the new version.

Thanks.

**Comment by Grokzen** [comment]
@umang92 The commit above should resolve the error inside the client so you most likley dont have to have some handling inside your code. The client will not try to resolve the case where slots is not covered like in your case and if it fails until TTL has expired then the underlying exception will be raised back to you to deal with. It is not a guaranted fix for all casees since it can still be thrown if TTL expires still.

**Comment by tzickel** [comment]
@Grokzen are you sure you put the "except SlotNotCoveredError as e" in the correct place ? shouldn't it cover this call as well ?

https://github.com/Grokzen/redis-py-cluster/blob/76aa25ffe4a9d009c0008ff83428d0e7e572f2e7/rediscluster/client.py#L581

**Comment by Miguelme** [comment]
Even with the refresh command it’s still happening for me using the docker bitnami image for redis-cluster

**Comment by Grokzen** [comment]
> @Grokzen are you sure you put the "except SlotNotCoveredError as e" in the correct place ? shouldn't it cover this call as well ?
> 
> https://github.com/Grokzen/redis-py-cluster/blob/76aa25ffe4a9d009c0008ff83428d0e7e572f2e7/rediscluster/client.py#L581

@tzickel Yes it might need to be covered as well to handle the SlotNotCoveredError exception that might be raised in certain conditions.

**Comment by Grokzen** [comment]
@Miguelme You need to provide much more information in what you are running, what version of components you are running and what error you are seeing when you are doing what. w/o steps to reproduce an error that you are seeing i can't really help you out right now.

**Comment by kuabhish** [comment]
Hey
I have written this 
```
try:
  rc.set("foor", "koor")
  print(rc.get('foor'))
except Exception as e:
  print(e)
  rc.refresh_table_asap = True
  ```
  
  Still I am getting the error
  `Slot "3280" not covered by the cluster. "skip_full_coverage_check=True"`
  
  Help.

**Comment by Grokzen** [comment]
@kuabhish The option flag `skip_full_coverage_check=True` only works to block the check when you create the RedisCluster object but as soon as you use it it will fail when you attempt to send a command to a slot that it do not know anything. This is intended behavior by the client and you must have all slots covered when you start to use the cluster and specially the slots you are trying to access with your set command

**Comment by kuabhish** [comment]
Hey @Grokzen  
Thanks for this quick reply. 
I don't understand what you said.
Do you mean I should start all the cluster nodes first and then create the cluster class?
If yes.
Then I already checked with redis-cli that it can connect to the nodes.

**Comment by Grokzen** [comment]
Yes that is what you must do, you need to create a proper cluster that has all 16k slots assigned to one of the master nodes in your cluster. Just having the nodes up and running do not help if your cluster is not setup properly please read up on the basics here https://redis.io/topics/cluster-tutorial and try again.

What all slots covered means is that you need to have all 16k slots assigned to at least one master node. In your case the slot 3280 for some reason is not assigned properly to a master node and thus is "not covered" when you attempt to ask the redis cluster what the current cluster setup is when query `CLUSTER SLOTS` command.
